publish:
  image: salesadriano/docker_publisher
  stage: build
  services:
    - docker:dind
  before_script: 
      - service docker start
      - sleep 5
  script:
    - docker build . -t $CI_PROJECT_NAME --pull
    - docker tag $CI_PROJECT_NAME $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME
    - /publicar.sh rancher/kubernetes.yml
  only:
    - master

