build:
  image: docker
  stage: build
  variables:
    IMAGE_TAG: etl:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u devseict -p S3ict2021
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG