stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}
- name: Deploy develop
  steps:
  - applyYamlConfig:
      path: ./kubernetes_dev.yml
  when:
    branch:
      include:
      - develop
- name: Deploy Prod
  steps:
  - applyYamlConfig:
      path: ./kubernetes_prod.yml
  when:
    branch:
      include:
      - master
branch:
  include:
  - develop
notification:
  recipients:
  - recipient: dev.seict@ac.gov.br
    notifier: c-4t79h:n-56xfw
  condition:
  - Success
  - Failed
