stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml  
    envFrom:
    - sourceName: variaveis
      sourceKey: dominio
      targetKey: DOMINIO
    env:
      DOMINIO: DOMINIO
branch:
  include:
  - develop
notification: {}
