stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}

- name: Deploy develop
  when: 
    branch: develop
  steps:
  - applyYamlConfig:
      path: ./kubernetes_dev.yml

- name: Deploy Prod
  when: 
    branch: master
  steps:
  - applyYamlConfig:
      path: ./kubernetes_prod.yml
branch:
  include:
  - master
  - develop
notification: {}
