stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
  - runScriptConfig:
      image: php:latest
      shellScript: echo ${DOMINIO}
    envFrom:
    - sourceName: variaveis
      sourceKey: dominio
      targetKey: DOMINIO
branch:
  include:
  - develop
notification: {}
