stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: devseict/etl:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_PASSWORD: PLUGIN_PASSWORD
      PLUGIN_USERNAME: devseict
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch: {}
notification: {}
