stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch:
  include:
  - master
notification:
  recipients:
  - recipient: dev.seict@ac.gov.br
    notifier: c-4t79h:n-56xfw
  condition:
  - Success
