stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch:
  include:
  - master
  exclude:
  - develop
notification:
  recipients:
  - recipient: dev.seict@ac.gov.br
    notifier: c-m-pbcp2k2k:n-5jrjk
  condition:
  - Success
  - Failed
