stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: devseict/etl:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch: {}
notification: {}
