stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"   
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch: {}
notification: {}
