stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: devseict/etl:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      DOCKER_DEBUG: "true"
      DOCKER_INSECURE: "true"
      DOCKER_PASSWORD: S31ct2021
      DOCKER_USERNAME: devseict
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch: {}
notification: {}
