stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: devseict/etl:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_EMAIL: PLUGIN_EMAIL
      PLUGIN_INSECURE: "true"
      PLUGIN_PASSWORD: PLUGIN_PASSWORD
      PLUGIN_USERNAME: PLUGIN_USERNAME
    envFrom:
    - sourceName: devseict-docker
      sourceKey: PLUGIN_EMAIL
    - sourceName: devseict-docker
      sourceKey: PLUGIN_PASSWORD
    - sourceName: devseict-docker
      sourceKey: PLUGIN_USERNAME
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
branch: {}
notification: {}
