stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: etl:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_BUILD_ARGS_FROM_ENV: dominio
    envFrom:
    - sourceName: variaveis
      sourceKey: dominio
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes.yml
    env:
      dominio: novoacre.gov.br
    envFrom:
    - sourceName: variaveis
      sourceKey: dominio
branch:
  include:
  - develop
notification:
  recipients:
  - recipient: dev.seict@ac.gov.br
    notifier: c-m-pbcp2k2k:n-5jrjk
  condition:
  - Success
  - Failed
