apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl
  namespace: default
spec:
  selector:
    matchLabels:
      app: etl
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etl
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: etl
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8000
              
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: etl
  namespace: default
spec:
  selector:
    app: etl
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP

---

# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etl
  namespace: default
spec:
  rules:
  - host: etl.${dominio}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: etl
            port:
              number: 80
