apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl
  namespace: seict
spec:
  selector:
    matchLabels:
      app: etl
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etl
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: etl
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
              
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: etl
  namespace: default
spec:
  selector:
    app: etl
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: etl
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: etl.ac.gov.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: etl
                port:
                  number: 80

