apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl1-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 80Mi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: etl
  namespace: default
  labels:
    allow.http: "false"
    application: etl
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      application: etl
  template:
    metadata:
      labels:
        application: etl
    spec:
      imagePullSecrets:
       - name: pipeline-docker-registry
      containers:
      - name: etl
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        # imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 22
        securityContext:
          privileged: true
        volumeMounts:
          - name:  etl-volume
            mountPath:  /code
      volumes:
      - name: etl-volume
        persistentVolumeClaim:
          claimName: etl1-pvc

