kind: Deployment
apiVersion: apps/v1
metadata:
  name: etl
  namespace: default
  labels:
    allow.http: "false"
    application: etl
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      application: etl
  template:
    metadata:
      labels:
        application: etl
    spec:
      imagePullSecrets:
       - name: pipeline-docker-registry
      containers:
      - name: etl
        image: ${CICD_REGISTRY}/etl:${CICD_EXECUTION_SEQUENCE}
        # imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 22
        securityContext:
          privileged: true

