kind: Deployment
apiVersion: apps/v1
metadata:
  name: etl
  namespace: seict
  labels:
    allow.http: "false"
    application: etl
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      application: etl
  template:
    metadata:
      labels:
        application: etl
    spec:
      imagePullSecrets:
       - name: pipeline-docker-registry
      containers:
      - name: etl1
        image: devseict/java8
        imagePullPolicy: Always
        resources:
          limits:
            memory: "16Gi"
            cpu: "1500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          privileged: true
        env:
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-kubernet
                key: GIT_USERNAME
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git-kubernet
                key: GIT_PASSWORD        
          - name: GIT_PATH
            value: gitlab.ac.gov.br/governoacre/seict/etlpentaho.git